### ISSUE TITLE
NullPointerException using the telemetry-all dependency

### ISSUE THREAD

**Issue by andyduncanitv** [newrelic/newrelic-telemetry-sdk-java#260]
Hi,

I'm seeing a NullPointerException when using the telemetry-all dependency rather than the individual dependencies:

```
0    [main] ERROR com.newrelic.telemetry.transport.BatchDataSender  - Error reading version. Defaulting to 'UnknownVersion'
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at com.newrelic.telemetry.transport.BatchDataSender.readVersion(BatchDataSender.java:217)
	at com.newrelic.telemetry.transport.BatchDataSender.<clinit>(BatchDataSender.java:46)
	at com.newrelic.telemetry.events.EventBatchSender.create(EventBatchSender.java:85)
	at com.newrelic.telemetry.events.EventBatchSender$create.call(Unknown Source)
```

This doesn't happen when using the telemetry, telemetry-core, and telemetry-http-java11 separately. I think this is because the telemetry-all packaging doesn't include the [generated version file](https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/main/telemetry-core/build.gradle.kts#L67).

**Comment by tbradellis** [comment]
https://github.com/newrelic/newrelic-telemetry-sdk-java/pull/266
